//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SysDesarrolloHEntities : DbContext
    {
        public SysDesarrolloHEntities()
            : base("name=SysDesarrolloHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ct_Plaza> Ct_Plaza { get; set; }
        public virtual DbSet<Ct_NivelCursos> Ct_NivelCursos { get; set; }
        public virtual DbSet<Tb_UsuariosCurso> Tb_UsuariosCurso { get; set; }
        public virtual DbSet<Ct_ActivoCursos> Ct_ActivoCursos { get; set; }
        public virtual DbSet<Ct_Colores> Ct_Colores { get; set; }
        public virtual DbSet<Ct_FormaPago> Ct_FormaPago { get; set; }
        public virtual DbSet<Ct_Roles> Ct_Roles { get; set; }
        public virtual DbSet<Ct_Status> Ct_Status { get; set; }
        public virtual DbSet<Tb_CarritoCompra> Tb_CarritoCompra { get; set; }
        public virtual DbSet<Tb_CarritoItem> Tb_CarritoItem { get; set; }
        public virtual DbSet<Tb_Categorias> Tb_Categorias { get; set; }
        public virtual DbSet<Tb_Contactos> Tb_Contactos { get; set; }
        public virtual DbSet<Tb_Direccion> Tb_Direccion { get; set; }
        public virtual DbSet<Tb_ImagenesProductos> Tb_ImagenesProductos { get; set; }
        public virtual DbSet<Tb_Lugares> Tb_Lugares { get; set; }
        public virtual DbSet<Tb_LugaresPases> Tb_LugaresPases { get; set; }
        public virtual DbSet<Tb_Marca> Tb_Marca { get; set; }
        public virtual DbSet<Tb_Mesas> Tb_Mesas { get; set; }
        public virtual DbSet<Tb_OrdenCompra> Tb_OrdenCompra { get; set; }
        public virtual DbSet<Tb_OrdenItem> Tb_OrdenItem { get; set; }
        public virtual DbSet<Tb_OrdenStatus> Tb_OrdenStatus { get; set; }
        public virtual DbSet<Tb_Productos> Tb_Productos { get; set; }
        public virtual DbSet<Tb_Tickets> Tb_Tickets { get; set; }
        public virtual DbSet<Tb_Usuarios> Tb_Usuarios { get; set; }
        public virtual DbSet<Tb_Vip> Tb_Vip { get; set; }
        public virtual DbSet<Tb_VipCon> Tb_VipCon { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<ipv6_database_firewall_rules> ipv6_database_firewall_rules { get; set; }
    
        [DbFunction("SysDesarrolloHEntities", "Func_Cuentas")]
        public virtual IQueryable<Func_Cuentas_Result> Func_Cuentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Func_Cuentas_Result>("[SysDesarrolloHEntities].[Func_Cuentas]()");
        }
    
        [DbFunction("SysDesarrolloHEntities", "Func_DatosAzul")]
        public virtual IQueryable<Func_DatosAzul_Result> Func_DatosAzul()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Func_DatosAzul_Result>("[SysDesarrolloHEntities].[Func_DatosAzul]()");
        }
    
        [DbFunction("SysDesarrolloHEntities", "Func_DatosRojo")]
        public virtual IQueryable<Func_DatosRojo_Result> Func_DatosRojo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Func_DatosRojo_Result>("[SysDesarrolloHEntities].[Func_DatosRojo]()");
        }
    
        [DbFunction("SysDesarrolloHEntities", "Func_DatosRosa")]
        public virtual IQueryable<Func_DatosRosa_Result> Func_DatosRosa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Func_DatosRosa_Result>("[SysDesarrolloHEntities].[Func_DatosRosa]()");
        }
    
        [DbFunction("SysDesarrolloHEntities", "Func_DatosVerde")]
        public virtual IQueryable<Func_DatosVerde_Result> Func_DatosVerde()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Func_DatosVerde_Result>("[SysDesarrolloHEntities].[Func_DatosVerde]()");
        }
    
        [DbFunction("SysDesarrolloHEntities", "Func_Reserva")]
        public virtual IQueryable<Func_Reserva_Result> Func_Reserva()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Func_Reserva_Result>("[SysDesarrolloHEntities].[Func_Reserva]()");
        }
    }
}
