//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Contactos
    {
        public System.Guid Lng_IdContacto { get; set; }
        public string Txt_Nombres { get; set; }
        public string Txt_Apellidos { get; set; }
        public string Txt_Correo { get; set; }
        public string Txt_Telefono { get; set; }
        public string Txt_Mensaje { get; set; }
    }
}
