//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Lugares
    {
        public System.Guid Lng_IdLugar { get; set; }
        public Nullable<System.Guid> Lng_IdProducto { get; set; }
        public string Txt_Lugar { get; set; }
        public Nullable<bool> Bol_Activo { get; set; }
        public string Txt_Nombre { get; set; }
        public string Txt_Email { get; set; }
        public string Txt_LigaPago { get; set; }
        public string Txt_Telefono { get; set; }
        public Nullable<int> Int_Color { get; set; }
        public Nullable<System.Guid> Int_IdUsuario { get; set; }
        public Nullable<bool> Bol_Compra { get; set; }
        public string Txt_CodigoApro { get; set; }
        public Nullable<bool> Bol_Status { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Compra { get; set; }
        public Nullable<int> Num_ContadorQR { get; set; }
        public Nullable<int> Int_Tipo { get; set; }
    }
}
