//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_LugaresPases
    {
        public System.Guid Lng_IdPase { get; set; }
        public Nullable<int> Int_Lugar { get; set; }
        public Nullable<int> Int_Color { get; set; }
        public Nullable<int> Num_ContadorQR { get; set; }
        public Nullable<bool> Bol_Status { get; set; }
        public Nullable<System.Guid> Lng_IdLugar { get; set; }
        public Nullable<int> Int_tipo { get; set; }
        public Nullable<bool> Bol_Mesa { get; set; }
        public Nullable<int> Num_Cantidad { get; set; }
        public string Txt_Nombre { get; set; }
        public string Txt_Nombrec { get; set; }
    }
}
