//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Mesas
    {
        public System.Guid Lng_IdMesas { get; set; }
        public Nullable<int> Int_IdColor { get; set; }
        public Nullable<decimal> Dbl_Valor { get; set; }
        public Nullable<int> Int_IdStatus { get; set; }
        public Nullable<int> Num_Personas { get; set; }
        public Nullable<int> Num_Mesa { get; set; }
        public Nullable<decimal> Dbl_ValorPes50 { get; set; }
        public Nullable<decimal> Dbl_ValorPes100 { get; set; }
        public Nullable<decimal> Dbl_ValorPes10 { get; set; }
        public Nullable<int> Int_IdFormaPago { get; set; }
    }
}
