//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_OrdenCompra
    {
        public System.Guid lng_IdOrdenCompra { get; set; }
        public Nullable<System.Guid> Lng_IdOrdenStatus { get; set; }
        public string Txt_FolioCompra { get; set; }
        public string Txt_Nombre { get; set; }
        public string Txt_Apellidos { get; set; }
        public string Txt_Correo { get; set; }
        public Nullable<decimal> Dbl_Total { get; set; }
        public Nullable<int> Int_PagoIntentoId { get; set; }
        public string Txt_MetodoPago { get; set; }
        public Nullable<System.Guid> Lng_IdUsuario { get; set; }
        public string Txt_IdTransaccion { get; set; }
        public Nullable<System.DateTime> Fec_Compra { get; set; }
        public string Qr_CodeCompra { get; set; }
        public Nullable<System.DateTime> Fec_Creo { get; set; }
        public string Txt_Autorizacion { get; set; }
    
        public virtual Tb_OrdenStatus Tb_OrdenStatus { get; set; }
    }
}
