//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_OrdenItem
    {
        public System.Guid Lng_IdOrdenItem { get; set; }
        public Nullable<System.Guid> lng_IdOrdenCompra { get; set; }
        public string Txt_Producto { get; set; }
        public Nullable<decimal> Dbl_Precio { get; set; }
        public Nullable<int> Int_Cantidad { get; set; }
        public Nullable<System.DateTime> Fec_Creo { get; set; }
        public byte[] Imagen { get; set; }
        public string Txt_Tipo { get; set; }
        public Nullable<System.Guid> Lng_IdProducto { get; set; }
    }
}
