//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Productos
    {
        public System.Guid Lng_IdProducto { get; set; }
        public string Txt_Nombre { get; set; }
        public string Txt_Sku { get; set; }
        public string Txt_Descripcion { get; set; }
        public Nullable<int> Int_Stock { get; set; }
        public Nullable<decimal> Dbl_Precio { get; set; }
        public Nullable<System.Guid> Lng_IdCategoria { get; set; }
        public Nullable<bool> Bol_Activo { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Edito { get; set; }
        public Nullable<System.Guid> Lng_IdUsuario { get; set; }
        public Nullable<int> WebSitio { get; set; }
    
        public virtual Tb_Categorias Tb_Categorias { get; set; }
    }
}
