//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Tickets
    {
        public System.Guid Lnd_IdIvitado { get; set; }
        public Nullable<System.Guid> Lng_IdOrdenItem { get; set; }
        public string Txt_NombreCompleto { get; set; }
        public string Txt_Correo { get; set; }
        public string Txt_Celular { get; set; }
        public string Qr_Code { get; set; }
        public Nullable<bool> Bol_Activo { get; set; }
        public Nullable<System.DateTime> Fec_Creo { get; set; }
        public Nullable<System.DateTime> Fec_Edito { get; set; }
    }
}
