//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Usuarios
    {
        public System.Guid Lng_IdUsuario { get; set; }
        public string Txt_Nombre { get; set; }
        public string Txt_Apellidos { get; set; }
        public string Txt_Password { get; set; }
        public string Txt_Correo { get; set; }
        public string Txt_Celular { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Edito { get; set; }
        public Nullable<System.Guid> Lng_IdRol { get; set; }
        public Nullable<bool> Bol_Activo { get; set; }
        public string Txt_SNombre { get; set; }
    }
}
