//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_VipCon
    {
        public System.Guid Lng_IdVipCon { get; set; }
        public Nullable<int> Int_IdTiket { get; set; }
        public Nullable<decimal> Dbl_PrecioDlls { get; set; }
        public Nullable<decimal> Dbl_Tc { get; set; }
        public Nullable<decimal> Dbl_PrecioPes { get; set; }
        public Nullable<decimal> Por_Gestion { get; set; }
        public Nullable<decimal> Dbl_ValGestion { get; set; }
        public Nullable<decimal> Dbl_Total { get; set; }
    }
}
